### PR TITLE
Font scaling and error handling

### PR DESCRIPTION
**Pull request by Kimmax**
- Subtext will be scaled down to fit subtext width
 - Enforced 56 character limit to subtext
 - Very basic error handling
--
@cozyplanes

### CODE REVIEW

**Comment by cozyplanes** [comment]
you mean when the subtext  is 55chars, it will be in 1 line, smaller size?

**Comment by cozyplanes** [comment]
@Kimmax

**Comment by Kimmax** [comment]
yes, It'll start off with with half the usernames font size (Currently 32px) and use it until it hit's the end of the line. If so, the complete line will be downscaled to fit the next character. Repeat until you hit the end of the text

**Comment by cozyplanes** [comment]
Please review typo

**Comment by Kimmax** [comment]
Whar typo..

**Comment by cozyplanes** [comment]
@Kimmax length in L43

**Comment by Kimmax** [comment]
you can comment directly on lines btw..

**Pull request merged**
